#-------------------------- Installing auditbeat ------------------------------
- name: check auditbeat installed or no
  stat: path=/etc/auditbeat/
  register: auditbeat

- debug: msg="auditbeat found, skip to next process"
  when: auditbeat.stat.exists == True

- debug: msg="auditbeat not found, prepare to install"
  when: auditbeat.stat.exists == False

- block:
  - name: download auditbeat from *.deb package
    register: result
    get_url:
      url="https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-6.2.2-amd64.deb"
      dest="/tmp/"

  - name: install it
    apt: deb="/tmp/auditbeat-6.2.2-amd64.deb" state="present"

- name: Copy all configuration for auditbeat and load templates to auditbeat
  template:
    src: templates/auditbeat.yml.j2
    dest: /etc/auditbeat/auditbeat.yml

- name: load template
  command: "{{item}}"
  with_items:
    - auditbeat setup --template -E output.logstash.enabled=false -E 'output.auditbeat.hosts=["{{elk_host}}:9200"]'
    - auditbeat setup --dashboards
    - systemctl enable auditbeat
    - systemctl start auditbeat
